### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by voipster** [rbonghi/docker-dropbox-app#31]
Hey,  getting this after it has been running successfully for a while, and I have to restart the container. 

```
dropbox - INFO - Request to files/list_folder
dropbox - INFO - Request to files/list_folder
dropbox - INFO - Request to files/list_folder
dropbox - INFO - Request to files/list_folder
dropbox - INFO - Request to files/list_folder
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/site-packages/dbsync-1.0.0-py3.11.egg/dbsync/updown.py", line 114, in run
    while not self.stopped.wait(self.interval):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/threading.py", line 323, in wait
    if timeout > 0:
       ^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by cgalvist** [comment]
I get the same error using the following docker compose:

```yaml
file-sync:
    image: rbonghi/dropbox:1.1.0
    command: ["--fromLocal", "-i", "60"]
    environment:
      - PYTHONUNBUFFERED=1
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
    volumes:
      - /media/data:/dropbox:ro
```

Replacing the `command` value from `["--fromLocal", "-i", "60"]` to `["--fromLocal"]` works for me

**Comment by AimPizza** [comment]
Managed to make it work and opened a PR ( #37 ). Can someone take a look?
